<script setup lang="ts">
import type { BTAppInfo } from '@/types/scan'
import dayjs from 'dayjs'
import { computed, nextTick, onUnmounted, ref, watch } from 'vue'
import { adaptProject, getAdaptableProjects } from '@/api/llm'
import { downloadReport, getAppInfoDetail, parseFileInfo } from '@/api/scan'
import ScanReportDialog from '@/components/scan/ScanReportDialog.vue'
import { download } from '@/utils/element'

const { t } = useI18n()

definePage({
  name: 'LlmAdapt',
  meta: {
    title: 'routes.llm.adapt',
    menu: false,
  },
})

// ==================== List state ====================
const projects = ref<BTAppInfo[]>([])
const loading = ref(false)
const keyword = ref('')
const viewMode = ref<'card' | 'table'>('card')

const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
  showSizeChanger: true,
  showTotal: (total: number) => t('llm.adapt.total-rows', { total }),
})

const tableColumns = [
  {
    title: t('llm.adapt.title-column'),
    dataIndex: 'name',
    key: 'name',
    minWidth: 180,
    ellipsis: true,
  },
  {
    title: t('llm.adapt.description-column'),
    dataIndex: 'description',
    key: 'description',
    minWidth: 200,
    ellipsis: true,
  },
  { title: t('llm.adapt.status-column'), key: 'status', width: 110 },
  {
    title: t('llm.adapt.package-column'),
    dataIndex: 'fileName',
    key: 'fileName',
    width: 160,
    ellipsis: true,
  },
  {
    title: t('llm.adapt.create-time-column'),
    dataIndex: 'createTime',
    key: 'createTime',
    width: 180,
  },
  { title: t('llm.adapt.actions-column'), key: 'action', width: 120 },
]

async function loadProjects() {
  loading.value = true
  try {
    const result = await getAdaptableProjects(
      pagination.current,
      pagination.pageSize,
      keyword.value || undefined,
    )
    projects.value = result.records
    pagination.total = result.total
  } catch (error) {
    window.$message.error(error instanceof Error ? error.message : t('llm.messages.load-failed'))
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  pagination.current = 1
  loadProjects()
}

function handlePageChange(page: number, pageSize: number) {
  pagination.current = page
  pagination.pageSize = pageSize
  loadProjects()
}

function getAdaptProgress(project: BTAppInfo): { text: string; percent: number } {
  // question-based progress
  const totalQ = parseNum(project.totalQuestion)
  const adaptQ = parseNum(project.adaptQuestion)
  if (totalQ > 0) {
    const pct = Math.round((adaptQ / totalQ) * 100)
    if (pct <= 0) return { text: t('llm.adapt.adapt-not-started'), percent: 0 }
    if (pct >= 100) return { text: t('llm.adapt.adapt-completed'), percent: 100 }
    return { text: `${pct}%`, percent: pct }
  }
  // file-based progress fallback
  const totalF = parseNum(project.totalQuestionFile)
  const adaptF = parseNum(project.adaptQuestionFile)
  if (totalF > 0) {
    const pct = Math.round((adaptF / totalF) * 100)
    if (pct <= 0) return { text: t('llm.adapt.adapt-not-started'), percent: 0 }
    if (pct >= 100) return { text: t('llm.adapt.adapt-completed'), percent: 100 }
    return { text: `${pct}%`, percent: pct }
  }
  // adapt status fallback
  if (project.adaptStatus === '-1') return { text: t('llm.adapt.adapt-completed'), percent: 100 }
  if (project.adaptStatus === '1') return { text: t('llm.adapt.adapt-in-progress'), percent: 0 }
  return { text: t('llm.adapt.adapt-not-started'), percent: 0 }
}

// ==================== Report dialog ====================
const reportDialogVisible = ref(false)
const reportTaskId = ref('')
const reportProjectId = ref('')
const reportProjectName = ref('')
const reportFileInfo = ref<Record<string, { fileCount: number; lineCount: number }> | null>(null)
const reportAdaptStatus = ref('')
const adaptProjectLoading = ref(false)

const batchFileProgress = ref({ done: 0, total: 0 })
const batchQuestionProgress = ref({ done: 0, total: 0 })

function parseNum(v: number | string | null | undefined): number {
  if (v === null || v === undefined) return 0
  if (typeof v === 'number') return v
  const n = Number(v)
  return Number.isNaN(n) ? 0 : n
}

const reportDialogRef = ref<InstanceType<typeof LightDialog>>()
const scanReportRef = ref<InstanceType<typeof ScanReportDialog>>()
/** Loading state of the "export AI adaptation report" action */
const exportingAdaptReport = ref(false)

/** Export the report generated by the AI adaptation (status=1) */
async function handleExportAdaptReport() {
  if (!reportProjectId.value || exportingAdaptReport.value) return
  exportingAdaptReport.value = true
  try {
    const { blob, filename } = await downloadReport(reportProjectId.value, '1')
    // Prefer the file name from the backend Content-Disposition, fall back to a local one
    download(blob, filename ?? `${reportProjectName.value}${t('scan.report.file-suffix')}.docx`)
  } catch (error) {
    window.$message.error(error instanceof Error ? error.message : t('scan.report.export-failed'))
  } finally {
    exportingAdaptReport.value = false
  }
}

async function openAdaptDialog(project: BTAppInfo) {
  try {
    const detail = await getAppInfoDetail(project.id)
    reportTaskId.value = detail.taskId || ''
    reportProjectId.value = project.id
    reportProjectName.value = detail.name
    reportAdaptStatus.value = detail.adaptStatus ?? ''
    // Fill in the progress data right away
    batchFileProgress.value = {
      done: parseNum(detail.adaptQuestionFile),
      total: parseNum(detail.totalQuestionFile),
    }
    batchQuestionProgress.value = {
      done: parseNum(detail.adaptQuestion),
      total: parseNum(detail.totalQuestion),
    }
    reportFileInfo.value = parseFileInfo(detail.fileInfo) as Record<
      string,
      { fileCount: number; lineCount: number }
    > | null
    reportDialogRef.value?.open()
    await nextTick()
    scanReportRef.value?.loadReportData()
    // Start progress polling if a batch adaptation is running
    if (reportAdaptStatus.value === '1') {
      startBatchProgressPolling()
    }
  } catch (error) {
    window.$message.error(error instanceof Error ? error.message : t('llm.messages.load-failed'))
  }
}

async function handleAdaptProject() {
  if (!reportTaskId.value) return
  adaptProjectLoading.value = true
  try {
    await adaptProject(reportTaskId.value)
    reportAdaptStatus.value = '1'
    startBatchProgressPolling()
    window.$message.success(t('llm.adapt.batch-adapt-success'))
  } catch (error) {
    window.$message.error(
      error instanceof Error ? error.message : t('llm.adapt.batch-adapt-failed'),
    )
  } finally {
    adaptProjectLoading.value = false
  }
}

const canBatchAdapt = computed(
  () => reportAdaptStatus.value === '0' || reportAdaptStatus.value === '',
)

const batchFileProgressText = computed(() => {
  if (batchFileProgress.value.total <= 0) return ''
  return `${batchFileProgress.value.done}/${batchFileProgress.value.total}`
})
const batchQuestionProgressText = computed(() => {
  if (batchQuestionProgress.value.total <= 0) return ''
  return `${batchQuestionProgress.value.done}/${batchQuestionProgress.value.total}`
})
const batchQuestionProgressPercent = computed(() => {
  if (batchQuestionProgress.value.total <= 0) return 0
  return Math.round((batchQuestionProgress.value.done / batchQuestionProgress.value.total) * 100)
})

let batchProgressTimer: ReturnType<typeof setInterval> | null = null

async function pollBatchProgress() {
  if (!reportDialogVisible.value || reportAdaptStatus.value !== '1') {
    stopBatchProgressPolling()
    return
  }
  try {
    const detail = await getAppInfoDetail(reportProjectId.value)
    const af = parseNum(detail.adaptQuestionFile)
    const tf = parseNum(detail.totalQuestionFile)
    const aq = parseNum(detail.adaptQuestion)
    const tq = parseNum(detail.totalQuestion)
    batchFileProgress.value = { done: af, total: tf }
    batchQuestionProgress.value = { done: aq, total: tq }
    reportAdaptStatus.value = detail.adaptStatus ?? '0'
    if (detail.adaptStatus === '-1') {
      stopBatchProgressPolling()
    }
  } catch {
    // Ignore polling failures
  }
}

function startBatchProgressPolling() {
  stopBatchProgressPolling()
  if (reportAdaptStatus.value !== '1' || !reportDialogVisible.value) return
  // Fetch once immediately
  pollBatchProgress()
  batchProgressTimer = setInterval(pollBatchProgress, 5000)
}

function stopBatchProgressPolling() {
  if (batchProgressTimer) {
    clearInterval(batchProgressTimer)
    batchProgressTimer = null
  }
}

onUnmounted(() => {
  stopBatchProgressPolling()
})

loadProjects()

// Refresh the list and stop polling after the dialog closes
watch(reportDialogVisible, (val) => {
  if (!val) {
    stopBatchProgressPolling()
    loadProjects()
  }
})
</script>

<template>
  <div>
    <!-- Top bar -->
    <div
      style="
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 30px;
      "
    >
      <div class="adapt-page-title" style="font-size: 18px; font-weight: 600">
        {{ t('routes.llm.adapt') }}
      </div>
      <div style="display: flex; gap: 12px">
        <div
          class="adapt-view-toggle"
          style="display: inline-flex; overflow: hidden; border-radius: 6px"
        >
          <AButton
            :type="viewMode === 'card' ? 'primary' : 'text'"
            size="small"
            style="height: 100%; padding: 4px 18px; border: none; border-radius: 0"
            @click="viewMode = 'card'"
          >
            <template #icon>
              <RenderIcon icon="i-ant-design:appstore-outlined" class="size-4" />
            </template>
          </AButton>
          <div class="adapt-view-toggle-divider" style="width: 1px" />
          <AButton
            :type="viewMode === 'table' ? 'primary' : 'text'"
            size="small"
            style="height: 100%; padding: 4px 18px; border: none; border-radius: 0"
            @click="viewMode = 'table'"
          >
            <template #icon>
              <RenderIcon icon="i-ant-design:unordered-list-outlined" class="size-4" />
            </template>
          </AButton>
        </div>
        <AInput
          v-model:value="keyword"
          :placeholder="t('llm.adapt.search-placeholder')"
          allow-clear
          style="width: 300px"
          @press-enter="handleSearch"
        />
        <AButton @click="handleSearch">{{ t('llm.adapt.search') }}</AButton>
      </div>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="py-12 text-center">
      <ASpin size="large" />
    </div>

    <!-- Empty -->
    <ACard
      v-else-if="projects.length === 0"
      class="adapt-empty-card py-20 text-center border-0 w-full shadow-none"
    >
      <div class="mb-6 flex justify-center">
        <RenderIcon
          v-if="keyword"
          icon="i-ant-design:search-outlined"
          class="adapt-empty-icon size-24"
        />
        <RenderIcon v-else icon="i-ant-design:inbox-outlined" class="adapt-empty-icon size-24" />
      </div>
      <div class="adapt-empty-title" style="margin-bottom: 12px; font-size: 22px; font-weight: 600">
        {{ keyword ? t('llm.adapt.no-search-results') : t('llm.adapt.no-projects') }}
      </div>
      <div class="adapt-empty-desc" style="font-size: 15px">
        {{ keyword ? t('llm.adapt.no-search-results-hint') : t('llm.adapt.no-projects-hint') }}
      </div>
    </ACard>

    <!-- Table view -->
    <ATable
      v-else-if="viewMode === 'table'"
      :data-source="projects"
      :columns="tableColumns"
      row-key="id"
      size="middle"
      :pagination="{
        ...pagination,
        onChange: handlePageChange,
        onShowSizeChange: handlePageChange,
      }"
    >
      <!-- antdv types this slot's `record` as AnyObject no matter the row type,
           so keep it loose here; the handlers below keep their own row signatures -->
      <template #bodyCell="{ column, record }: { column: any; record: any }">
        <template v-if="column.key === 'status'">
          <ATag
            :color="
              getAdaptProgress(record).percent >= 100
                ? 'success'
                : getAdaptProgress(record).percent > 0
                  ? 'processing'
                  : 'default'
            "
          >
            {{ getAdaptProgress(record).text }}
          </ATag>
        </template>
        <template v-else-if="column.key === 'createTime'">
          {{ record.createTime ? dayjs(record.createTime).format('YYYY-MM-DD HH:mm:ss') : '-' }}
        </template>
        <template v-else-if="column.key === 'action'">
          <AButton type="link" size="small" @click="openAdaptDialog(record)">
            {{ t('llm.adapt.view-details') }}
          </AButton>
        </template>
      </template>
    </ATable>

    <!-- Card view -->
    <div
      v-else
      class="adapt-card-grid"
      style="display: grid; grid-template-columns: repeat(auto-fill, minmax(370px, 1fr)); gap: 20px"
    >
      <div
        v-for="project in projects"
        :key="project.id"
        class="adapt-card"
        style="
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          min-height: 120px;
          padding: 20px;
          border-radius: 10px;
        "
      >
        <div style="display: flex; align-items: flex-start; justify-content: space-between">
          <div
            class="adapt-card-name"
            style="
              min-width: 0;
              overflow: hidden;
              text-overflow: ellipsis;
              font-family: 'Microsoft YaHei', sans-serif;
              font-size: 24px;
              font-variation-settings: 'opsz' auto;
              font-weight: bold;
              line-height: 24px;
              letter-spacing: 0em;
              white-space: nowrap;
            "
          >
            {{ project.name }}
          </div>
        </div>

        <div style="display: flex; flex-direction: column; gap: 8px; margin-top: 16px">
          <div style="display: flex; gap: 8px; align-items: center">
            <ATag
              :color="
                getAdaptProgress(project).percent >= 100
                  ? 'success'
                  : getAdaptProgress(project).percent > 0
                    ? 'processing'
                    : 'default'
              "
              style="margin: 0"
            >
              {{ getAdaptProgress(project).text }}
            </ATag>
            <span v-if="project.fileName" class="adapt-card-filename" style="font-size: 13px">
              {{ project.fileName }}
            </span>
          </div>
        </div>

        <div style="display: flex; flex-direction: column; gap: 10px; margin-top: 16px">
          <div
            class="adapt-card-meta"
            style="
              display: flex;
              gap: 6px;
              align-items: center;
              font-family: 'Helvetica Neue LT Pro', sans-serif;
              font-size: 15px;
              font-weight: normal;
              line-height: 22px;
              letter-spacing: 0.05em;
            "
          >
            <RenderIcon icon="i-ant-design:calendar-outlined" class="size-4" />
            <span
              >{{ t('llm.adapt.create-time-column') }}：{{
                project.createTime ? dayjs(project.createTime).format('YYYY-MM-DD HH:mm:ss') : '-'
              }}</span
            >
          </div>
          <div
            v-if="project.description"
            class="adapt-card-meta--dim"
            style="
              display: flex;
              gap: 6px;
              align-items: center;
              font-family: 'Helvetica Neue LT Pro', sans-serif;
              font-size: 14px;
              font-weight: normal;
              line-height: 22px;
              letter-spacing: 0.05em;
            "
          >
            <RenderIcon icon="i-ant-design:file-text-outlined" class="size-4" />
            <span style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{
              project.description
            }}</span>
          </div>
        </div>

        <div style="display: flex; justify-content: flex-end; margin-top: 12px">
          <AButton
            class="adapt-card-action"
            style="
              display: flex;
              flex-direction: column;
              gap: 10px;
              align-items: center;
              justify-content: center;
              width: 100%;
              padding: 8px 10px;
              font-family: 'Microsoft YaHei', sans-serif;
              font-size: 16px;
              font-variation-settings: 'opsz' auto;
              font-weight: normal;
              line-height: normal;
              letter-spacing: 0em;
              border: none;
              border-radius: 4px;
            "
            @click="openAdaptDialog(project)"
            >{{ t('llm.adapt.view-details') }}</AButton
          >
        </div>
      </div>
    </div>

    <!-- Adapt result dialog -->
    <LightDialog
      ref="reportDialogRef"
      v-model:open="reportDialogVisible"
      width="1840px"
      height="auto"
      padding="30px"
    >
      <template #title>
        {{ t('llm.adapt.result') }}
      </template>
      <template #extra>
        <div class="adapt-dialog-extra">
          <!-- Batch adaptation progress: modelled on GlobalProgressBar -->
          <div v-if="reportAdaptStatus === '1'" class="adapt-dialog-progress">
            <div class="text-blue-600 text-xs font-medium flex shrink-0 gap-1.5 items-center">
              <RenderIcon icon="i-ant-design:loading-outlined" class="size-3.5 animate-spin" />
              <span>{{ t('llm.adapt.batch-adapting') }}</span>
            </div>
            <div class="adapt-dialog-progress-bar">
              <div
                class="adapt-dialog-progress-fill"
                :style="{ width: `${batchQuestionProgressPercent}%` }"
              />
            </div>
            <span class="adapt-dialog-progress-pct">{{ batchQuestionProgressPercent }}%</span>
            <span class="adapt-dialog-progress-summary">
              {{ t('llm.adapt.question-progress') }}
              <span class="text-slate-600 font-medium">{{
                batchQuestionProgressText || '0/0'
              }}</span>
              · {{ t('llm.adapt.file-progress') }}
              <span class="text-slate-600 font-medium">{{ batchFileProgressText || '0/0' }}</span>
            </span>
          </div>
          <!-- Adapted: icon + text -->
          <div v-if="reportAdaptStatus === '-1'" class="adapt-batch-done">
            <RenderIcon icon="i-ant-design:check-circle-outlined" class="size-4" />
            <span>{{ t('llm.adapt.batch-adapted') }}</span>
          </div>
          <!-- Not adapted / adapting: button -->
          <AButton
            v-else
            type="primary"
            size="small"
            :loading="adaptProjectLoading"
            :disabled="!canBatchAdapt"
            @click="handleAdaptProject"
          >
            {{
              reportAdaptStatus === '1' ? t('llm.adapt.batch-adapting') : t('llm.adapt.batch-adapt')
            }}
          </AButton>
          <LightLink
            class="btn"
            style="
              display: inline-flex;
              gap: 8px;
              align-items: center;
              margin-right: 20px;
              color: #333;
              text-decoration: none;
              cursor: pointer;
            "
            :style="exportingAdaptReport ? { pointerEvents: 'none', opacity: 0.6 } : {}"
            @click="handleExportAdaptReport"
          >
            <img
              class="icon"
              src="@/assets/svg/report-export.svg"
              alt=""
              style="width: 20px; height: 20px"
            />
            <span class="text" style="font-size: 16px">
              {{
                exportingAdaptReport
                  ? t('scan.report.exporting')
                  : t('scan.report.export-adapt-report')
              }}
            </span>
          </LightLink>
          <LightButton @click="reportDialogVisible = false">
            <img class="icon small" src="@/assets/svg/close.svg" alt="" />
            <span class="text">{{ t('common.close') }}</span>
          </LightButton>
        </div>
      </template>
      <ScanReportDialog
        ref="scanReportRef"
        :task-id="reportTaskId"
        :project-id="reportProjectId"
        :project-name="reportProjectName"
        :file-info="reportFileInfo"
        :show-overview="false"
        :show-adapt="true"
      />
    </LightDialog>
  </div>
</template>

<style lang="scss">
/* ===== Light mode defaults ===== */
.adapt-page-title {
  color: #333;
}

.adapt-view-toggle {
  border: 1px solid #d9d9d9;
}

.adapt-view-toggle-divider {
  background: #d9d9d9;
}

.adapt-empty-card {
  /* ACard handles its own bg in dark via antdv-next theme */
}

.adapt-empty-icon {
  color: #e2e8f0;
}

.adapt-empty-title {
  color: #94a3b8;
}

.adapt-empty-desc {
  color: #94a3b8;
}

.adapt-card {
  background: #f9fbff;
  box-shadow: 0px 4px 32px 0px rgba(160, 175, 222, 0.2);
}

.adapt-card-name {
  color: #000;
}

.adapt-card-filename {
  color: #94a3b8;
}

.adapt-card-meta {
  color: #7182a8;
}

.adapt-card-meta--dim {
  color: #94a3b8;
}

.adapt-card-action {
  color: #3578ff;
  background: rgba(53, 120, 255, 0.1);
}

/* ===== Dark mode overrides ===== */
.dark .adapt-page-title {
  color: #e8edf5;
}

.dark .adapt-view-toggle {
  border-color: #2a3050;
}

.dark .adapt-view-toggle-divider {
  background: #2a3050;
}

.dark .adapt-empty-icon {
  color: #334155;
}

.dark .adapt-empty-title {
  color: #475569;
}

.dark .adapt-empty-desc {
  color: #475569;
}

.dark .adapt-card {
  background: #1a1f2e;
  box-shadow: 0px 4px 32px 0px rgba(0, 0, 0, 0.35);
}

.dark .adapt-card-name {
  color: #e8edf5;
}

.dark .adapt-card-filename {
  color: #6b7a9e;
}

.dark .adapt-card-meta {
  color: #a0adde;
}

.dark .adapt-card-meta--dim {
  color: #6b7a9e;
}

.dark .adapt-card-action {
  color: #60a5fa;
  background: rgba(96, 165, 250, 0.12);
}

/* ===== Dark mode overrides for progress ===== */
.dark .adapt-dialog-progress-bar {
  background: #2a3050;
}

.dark .adapt-dialog-progress-fill {
  background: linear-gradient(90deg, #60a5fa, #93c5fd);
}

.dark .adapt-dialog-progress-pct {
  color: #93c5fd;
}

.dark .adapt-dialog-progress-summary {
  color: #6b7a9e;
}

/* ===== Dialog extra area (top-right) ===== */
.adapt-dialog-extra {
  display: flex;
  gap: 16px;
  align-items: center;
}

/* ===== Batch progress (single-row, inspired by GlobalProgressBar) ===== */
.adapt-dialog-progress {
  display: flex;
  flex: 1;
  gap: 10px;
  align-items: center;
  min-width: 0;
}

.adapt-dialog-progress-bar {
  flex: 1;
  min-width: 60px;
  height: 5px;
  overflow: hidden;
  background: #e8edf5;
  border-radius: 3px;
}

.adapt-dialog-progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #3578ff, #60a5fa);
  border-radius: 3px;
  transition: width 0.5s ease;
}

.adapt-dialog-progress-pct {
  flex-shrink: 0;
  font-size: 11px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  color: #3578ff;
}

.adapt-dialog-progress-summary {
  flex-shrink: 0;
  font-size: 11px;
  color: #94a3b8;
  white-space: nowrap;
}

.adapt-dialog-title-text {
  flex-shrink: 0;
}

.adapt-dialog-title-right {
  display: flex;
  gap: 12px;
  align-items: center;
  min-width: 0;
}

/* ===== Done state ===== */
.adapt-batch-done {
  display: flex;
  gap: 6px;
  align-items: center;
  font-size: 13px;
  font-weight: 500;
  color: #52c41a;
  white-space: nowrap;
}

/* ===== Dark mode overrides for progress ===== */
.dark .adapt-batch-progress-label {
  color: #6b7a9e;
}

.dark .adapt-batch-progress-bar {
  background: #2a3050;
}

.dark .adapt-batch-progress-fill {
  background: linear-gradient(90deg, #60a5fa, #93c5fd);
}

.dark .adapt-batch-progress-text {
  color: #93c5fd;
}
</style>
